defaults:

        scope:
                path: "" # all files in project
                type: ""
        values:
                name: Jason Smith
                markdown: kramdown
                author:      "Dr. Jekyll"
                jason_plain: "Mr. Jason Smith"
                jason:       "<span class=\"sc\">Mr. Jason Smith</span>"

        scope:
                path: ""
                type: "pages"
        values:
                author:      "Mr. Hyde"
                jason_plain: "Jason Smith"
                jason:       "<span class=\"sc\">Jason Smith</span>"

        scope:
                path: ""
                type: "posts"
        values:
                permalink: /blog/:year/:month/:day/:title

gems:
        - jekyll-feed

jason_plain: "Juan Valdez"
jason:       "<span class=\"sc\">Juan Valdez</span>"
