defaults:

        scope:
                path: "" # all files in project
                type: ""
        values:
                name: Jason Smith
                markdown: kramdown

        scope:
                path: ""
                type: "posts"
        values:
                permalink: /blog/:year/:month/:day/:title

gems:
        - jekyll-feed

